name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          CGV_DIR: /home/runner/work/cgv
          CGV_BUILD: abc
        run: |
          pwd
          ls -la
          sudo apt-get install -y doxygen
#          doxygen doc/cgv.dox

#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: build # The folder the action should deploy.
