name: Build and Install the CGV framework

on: push

jobs:
  build-ubuntu:
    name: "Ubuntu: Build and Install the CGV framework"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install llvm repository
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 11

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-tools-11 clang-11-doc libclang-11-dev

      - name: Install cgv dependencies
        run: sudo apt install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev xorg-dev

      - run: mkdir build

      - name: Run CMake
        working-directory: ./build
        run: cmake -G Ninja -D CMAKE_C_COMPILER=/usr/bin/clang-11 -D CMAKE_CXX_COMPILER=/usr/bin/clang++-11 -D CMAKE_INSTALL_PREFIX=../install ..

      - name: Build and Install
        working-directory: ./build
        run: xvfb-run cmake --build . --target install

      - name: Upload Install zip for Ubuntu
        uses: actions/upload-artifact@v2
        with:
          name: cgv-install-ubuntu
          path: ./install

  build-windows:
    name: "Windows: Build and Install the CGV framework"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up environment variables
        run: |
          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: cmake -D CMAKE_INSTALL_PREFIX=../install ..

      - name: Build and Install
        working-directory: ./build
        run: cmake --build . --target install

      - name: Upload Install zip for Windows
        uses: actions/upload-artifact@v2
        with:
          name: cgv-install-windows
          path: ./install

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows]
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - run: zip -r cgv-install-ubuntu.zip cgv-install-ubuntu
      - run: zip -r cgv-install-windows.zip cgv-install-ubuntu

      - name: Release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            cgv-install-ubuntu.zip
            cgv-install-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
